# Base configs
baseurl: "https://photography.imhussa.in"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Mubaraque Hussain"
subtitle: "See the world through my lens!"
author: "Mubaraque Hussain"
header:
 title: "Photography"
 subtitle: "by Ram Patra"
footer:
 name: "Hey there, my name is Ram"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/IamMubaraqueHussain"
  twitter: "https://www.twitter.com/IamMHussain"
  instagram: "https://www.instagram.com/imluckyhussain"
  dribbble: "https://dribbble.com/imhussain"
  linkedin: "https://in.linkedin.com/in/mubaraque"
  github: "https://www.github.com/imluckyhussain"

theme: jekyll-theme-cayman